packages:
  - 'understand-anything-plugin/packages/*'
  - 'understand-anything-plugin'
  - 'homepage'

onlyBuiltDependencies:
  - esbuild
  - sharp
  - tree-sitter-c
  - tree-sitter-c-sharp
  - tree-sitter-cpp
  - tree-sitter-go
  - tree-sitter-java
  - tree-sitter-javascript
  - tree-sitter-php
  - tree-sitter-python
  - tree-sitter-ruby
  - tree-sitter-rust
  - tree-sitter-typescript
